crop_thresh: 0.5
attr_thresh: 0.5
kpt_thresh: 0.2
visual: True
warmup_frame: 50
preview: rtsp://sub.codermax.cn:38554/live/preview

DET:
  model_dir: /mnt/models/mot_ppyoloe_s_36e_pipeline
  batch_size: 1

MOT:
  model_dir: /mnt/models/mot_ppyoloe_s_36e_pipeline
  tracker_config: deploy/pipeline/config/tracker_config.yml
  batch_size: 1
  skip_frame_num: 15 # preferably no more than 3
  enable: True